# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('SELECT', 'Select'), ('ADMIN', 'Admin'), ('REGULAR', 'Regular')], default='REGULAR', max_length=20),
        ),
    ]
